// Code generated by "stringer -type boxType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[blockBox-0]
	_ = x[inlineBox-1]
	_ = x[textBox-2]
	_ = x[anonymousBox-3]
	_ = x[rootBox-4]
}

const _boxType_name = "blockBoxinlineBoxtextBoxanonymousBoxrootBox"

var _boxType_index = [...]uint8{0, 8, 17, 24, 36, 43}

func (i boxType) String() string {
	if i < 0 || i >= boxType(len(_boxType_index)-1) {
		return "boxType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _boxType_name[_boxType_index[i]:_boxType_index[i+1]]
}
