// Code generated by "stringer -type Smotr smotr.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Onee-1]
	_ = x[Twoe-2]
	_ = x[Three-3]
}

const _Smotr_name = "OneeTwoeThree"

var _Smotr_index = [...]uint8{0, 4, 8, 13}

func (i Smotr) String() string {
	i -= 1
	if i < 0 || i >= Smotr(len(_Smotr_index)-1) {
		return "Smotr(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Smotr_name[_Smotr_index[i]:_Smotr_index[i+1]]
}
