// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[less-0]
	_ = x[greater-1]
	_ = x[lessSlash-2]
	_ = x[text-3]
	_ = x[ws-4]
	_ = x[equal-5]
	_ = x[stringTok-6]
	_ = x[eof-7]
}

const _TokenType_name = "lessgreaterlessSlashtextwsequalstringTokeof"

var _TokenType_index = [...]uint8{0, 4, 11, 20, 24, 26, 31, 40, 43}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
